from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.user import User
from app.models.skill import UserSkill
from app.models.resume import Resume
from app.models.roadmap import LearningRoadmap, RoadmapItem
from app.schemas.roadmap import RoadmapCreateRequest, RoadmapOut, RoadmapItemUpdate, RoadmapItemOut
from app.services.roadmap_service import roadmap_service
from app.api.deps import get_current_user

router = APIRouter(prefix="/roadmap", tags=["Learning Roadmap"])

@router.post("/generate", response_model=RoadmapOut, status_code=status.HTTP_201_CREATED)
async def generate_learning_roadmap(
    payload: RoadmapCreateRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Generate a personalized 5-phase career learning roadmap based on target role and current skill gaps.
    """
    # Fetch current skills from UserSkill and latest resume
    user_skills_records = db.query(UserSkill).filter(UserSkill.user_id == current_user.id).all()
    current_skills = [s.skill_name for s in user_skills_records]
    existing_lower = set(s.lower() for s in current_skills)

    latest_resume = db.query(Resume).filter(Resume.user_id == current_user.id).order_by(Resume.id.desc()).first()
    if latest_resume and latest_resume.analysis and latest_resume.analysis.detected_skills:
        for r_skill in latest_resume.analysis.detected_skills:
            s_name = r_skill["name"] if isinstance(r_skill, dict) else str(r_skill)
            if s_name and s_name.lower() not in existing_lower:
                current_skills.append(s_name)
                existing_lower.add(s_name.lower())

    if not current_skills and getattr(current_user, "is_demo", False):
        current_skills = [
            "Python", "PyTorch", "TensorFlow", "FastAPI", "Docker", "PostgreSQL",
            "SQL", "Git", "Scikit-Learn", "Pandas", "NumPy", "C++", "Java", "Linux", "REST APIs"
        ]

    roadmap_data = await roadmap_service.generate_roadmap(
        target_role=payload.target_role,
        current_skills=current_skills
    )

    new_roadmap = LearningRoadmap(
        user_id=current_user.id,
        target_role=roadmap_data["target_role"],
        title=roadmap_data["title"],
        description=roadmap_data["description"],
        progress_percentage=roadmap_data["progress_percentage"]
    )
    db.add(new_roadmap)
    db.commit()
    db.refresh(new_roadmap)

    # Insert items
    for item in roadmap_data["items"]:
        new_item = RoadmapItem(
            roadmap_id=new_roadmap.id,
            phase_number=item["phase_number"],
            phase_name=item["phase_name"],
            skill_name=item["skill_name"],
            priority=item["priority"],
            difficulty=item["difficulty"],
            estimated_hours=item["estimated_hours"],
            prerequisites=item["prerequisites"],
            project_idea=item["project_idea"],
            status=item["status"],
            order_index=item["order_index"]
        )
        db.add(new_item)

    db.commit()
    db.refresh(new_roadmap)

    return new_roadmap

@router.get("/latest", response_model=RoadmapOut)
def get_latest_roadmap(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieve the most recent learning roadmap for student."""
    roadmap = db.query(LearningRoadmap).filter(
        LearningRoadmap.user_id == current_user.id
    ).order_by(LearningRoadmap.id.desc()).first()
    
    if not roadmap:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No roadmap generated yet. Please generate a roadmap first."
        )
    return roadmap

@router.get("/history", response_model=List[RoadmapOut])
def get_roadmap_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieve list of all roadmaps generated by student."""
    roadmaps = db.query(LearningRoadmap).filter(
        LearningRoadmap.user_id == current_user.id
    ).order_by(LearningRoadmap.id.desc()).all()
    return roadmaps

@router.patch("/items/{item_id}", response_model=RoadmapItemOut)
def update_roadmap_item_status(
    item_id: int,
    payload: RoadmapItemUpdate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Update progress status for an individual skill roadmap item
    (not_started | in_progress | completed) and recalculate roadmap completion percentage.
    """
    valid_statuses = ["not_started", "in_progress", "completed"]
    if payload.status not in valid_statuses:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Status must be one of {valid_statuses}"
        )

    item = db.query(RoadmapItem).join(LearningRoadmap).filter(
        RoadmapItem.id == item_id,
        LearningRoadmap.user_id == current_user.id
    ).first()

    if not item:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Roadmap item not found.")

    item.status = payload.status
    db.commit()

    # Recalculate roadmap overall progress percentage
    roadmap = item.roadmap
    all_items = roadmap.items
    completed_count = sum(1 for it in all_items if it.status == "completed")
    in_progress_count = sum(1 for it in all_items if it.status == "in_progress")
    # Weighted progress: completed = 100%, in_progress = 50%
    total_score = (completed_count * 1.0) + (in_progress_count * 0.5)
    roadmap.progress_percentage = round((total_score / len(all_items)) * 100, 1) if all_items else 0.0

    db.commit()
    db.refresh(item)
    return item
